name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  release:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build and install debug
      run: |
        cmake --preset x64-Debug .
        cmake --build _build/x64-Debug --parallel
        cmake --install _build/x64-Debug

    - name: Build and install release
      run: |
        cmake --preset x64-Release .
        cmake --build _build/x64-Release --parallel
        cmake --install _build/x64-Release

    - name: Copy debug artifacts
      run: |
        mkdir _dist-debug
        Copy-Item _install/x64-Debug/bin/* -Destination _dist-debug/ -Recurse
        Copy-Item LICENSE -Destination _dist-debug/LICENSE

    - name: Copy release artifacts
      run: |
        mkdir _dist-release
        Copy-Item _install/x64-Release/bin/* -Destination _dist-release/ -Recurse
        Copy-Item LICENSE -Destination _dist-release/LICENSE

    - name: Archive debug
      uses: actions/upload-artifact@v3
      with:
        name: MyMod-Debug
        path: _dist-debug/*

    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: MyMod-Release
        path: _dist-release/*

  pre-release:
    name: Pre Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download debug artifact
      uses: actions/download-artifact@v3
      with:
        name: MyMod-Debug
        path: MyMod-Debug

    - name: Download release artifact
      uses: actions/download-artifact@v3
      with:
        name: MyMod-Release
        path: MyMod-Release

    - name: Archive artifact files
      run: |
        cd MyMod-Debug
        zip -r MyMod-Debug.zip *
        cd ../MyMod-Release
        zip -r MyMod-Release.zip *
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          MyMod-Debug/MyMod-Debug.zip
          MyMod-Release/MyMod-Release.zip

          
